name = "dockercustomize"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true
link_sdk = true
runtime_image = "debian"
build_base_image = "golang:1.16-buster"
enable_go_build_cache = true

[builders."docker:go"]
enabled = true
runtime_image = "debian"
build_base_image = "golang:1.16-buster"
enable_go_build_cache = true
# skip_runtime_image = true

[extra_sources]
   docker_generic = [ "../.." ]

[runners."local:docker"]
enabled = true

[[testcases]]
name = "account_state"
instances = { min = 1, max = 1, default = 1 }
