name = "mining"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "transaction"
instances = { min = 6, max = 100000000, default = 6 }

[[testcases]]
name = "new_account"
instances = { min = 6, max = 100000000, default = 6 }
